# SPDX-FileCopyrightText: 2023 Adafruit Industries
#
# SPDX-License-Identifier: MIT

# This is where you store the credentials necessary for your code.
# The associated demo only requires WiFi, but you can include any
# credentials here, such as Adafruit IO username and key, etc.
CIRCUITPY_WIFI_SSID = "CIRCUITPY_WIFI_SSID"
CIRCUITPY_WIFI_PASSWORD = "CIRCUITPY_WIFI_PASSWORD"
MQTT_BROKER = "IP.FOR.MQTT_BROKER"
MQTT_PORT = 1883
MQTT_USERNAME = "homeassistant"
MQTT_PASSWORD = "MQTT_USERNAME"