CIRCUITPY_WIFI_SSID = "CIRCUITPY_WIFI_SSID"
CIRCUITPY_WIFI_PASSWORD = "CIRCUITPY_WIFI_PASSWORD"

LOCATION = "City, State"
LATITUDE = "LATITUDE"
LONGITUDE = "LONGITUDE"
TIMEZONE = "US/Mountain"
TIMEZONE_OFFSET = -6
MEASUREMENT_UNITS = "IMPERIAL"