CIRCUITPY_WIFI_SSID = "NotGoodButGoodEnough"
CIRCUITPY_WIFI_PASSWORD = "strongcello751"

LOCATION = "Missoula, MT"
LATITUDE = "46.873101"
LONGITUDE = "-113.979988"
TIMEZONE = "US/Mountain"
TIMEZONE_OFFSET = -6
MEASUREMENT_UNITS = "IMPERIAL"